### ISSUE TITLE
Not an issue, just a pointer

### ISSUE THREAD

**Issue by tbone-gr8dy** [mstefanowich/SquiddlyDiddly2#1]
You'd have a higher success rate with setting it up as a two stage dropper.

**Comment by tbone-gr8dy** [comment]
You could do something similiar to Industroyer have it be a two stage dropper that installs additional backdoor(s) and tools. just sugessting

**Comment by mstefanowich** [comment]
Sorry for the late response, I've been sick but I'm finally starting to get back into the swing of things (step throat :( ). I agree with what you're saying, for the time being I'm trying to get this component working. Can you toss me additional information on this though? My initial thought was packing the data into the file via the resource section or an additional section of the PE file and extracting on run time (file inside of a file ;D ) but I'm not sure yet.
